export interface FacultyMember {
  name: string;
  designation: string;
  department: string;
  program: "Degree" | "Diploma" | "Postgraduate";
  qualification: string;
  specialization: string;
  type: "teaching" | "technical";
  isHod?: boolean;
  isPrincipal?: boolean;
  profileUrl?: string;
  email?: string;
  image?: string;
}

export const FACULTY_DATA: Record<string, { teaching: FacultyMember[]; technical?: FacultyMember[] }> = {
  // 1. Computer Engineering (Degree)
  "degree-computer": {
    teaching: [
      {
        name: "Dr. Vishal G. Barot",
        designation: "Head of Department & Assistant Professor",
        department: "Computer Engineering",
        program: "Degree",
        qualification: "Ph.D. in Computer Science & Engineering, M.E.",
        specialization: "Artificial Intelligence, Data Science & Machine Learning",
        type: "teaching",
        isHod: true,
        profileUrl: "/faculty-profile",
        email: "vishal.barot@gtu.edu.in",
        image: "/vishal-barot.jpg",
      },
      {
        name: "Prof. Hemalben M. Patel",
        designation: "Assistant Professor & WDC Convener",
        department: "Computer Engineering",
        program: "Degree",
        qualification: "M.E. in Computer Engineering",
        specialization: "Cloud Computing, Computer Networks & Cyber Security",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/compFac.aspx?ID=29",
        email: "hemal.patel@gtu.edu.in",
        image: "/faculty/hemal-patel.jpg",
      },
      {
        name: "Prof. Shilpa Vasava",
        designation: "Assistant Professor",
        department: "Computer Engineering",
        program: "Degree",
        qualification: "M.E. in Computer Engineering",
        specialization: "Database Management Systems, Software Engineering & Web Technologies",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/compFac.aspx?ID=19",
        email: "shilpa.vasava@gtu.edu.in",
        image: "/faculty/shilpa-vasava.jpg",
      },
      {
        name: "Prof. Vijay Punjabhai Khata",
        designation: "Assistant Professor",
        department: "Computer Engineering",
        program: "Degree",
        qualification: "M.Tech / M.E. in Computer Engineering",
        specialization: "Algorithms, Data Structures & Systems Programming",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/compFac.aspx?ID=27",
        email: "vijay.khata@gtu.edu.in",
        image: "/faculty/vijay-khata.jpg",
      },
      {
        name: "Prof. Hinal Prajapati",
        designation: "Assistant Professor",
        department: "Computer Engineering",
        program: "Degree",
        qualification: "M.E. in Computer Engineering",
        specialization: "Web Technologies, Object-Oriented Programming & Python",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/compFac.aspx?ID=18",
        email: "hinal.prajapati@gtu.edu.in",
        image: "/faculty/hinal-prajapati.jpg",
      },
    ],
    technical: [
      {
        name: "Mr. Dhrudipkumar Amaratbhai Chaudhary",
        designation: "System Analyst & Lab Assistant",
        department: "Computer Engineering",
        program: "Degree",
        qualification: "B.E. / Diploma in Computer Engineering",
        specialization: "Network Administration, Server Infrastructure & Lab Maintenance",
        type: "technical",
        profileUrl: "https://gtuitr.gtu.ac.in/compFac13.aspx",
      },
      {
        name: "Ms. Hani Gupta",
        designation: "Lab Assistant",
        department: "Computer Engineering",
        program: "Degree",
        qualification: "Diploma / B.Sc. in Computer Science",
        specialization: "Software Lab Administration & Operating Systems Support",
        type: "technical",
        profileUrl: "https://gtuitr.gtu.ac.in/compFac18.aspx",
      },
      {
        name: "Ms. Hiral Patel",
        designation: "Lab Assistant",
        department: "Computer Engineering",
        program: "Degree",
        qualification: "Diploma in Computer Engineering",
        specialization: "Programming Lab Assistance & Hardware Maintenance",
        type: "technical",
        profileUrl: "https://gtuitr.gtu.ac.in/TechnicalcompFac19.aspx",
      },
    ],
  },

  // 2. Mechanical Engineering (Degree)
  "degree-mechanical": {
    teaching: [
      {
        name: "Dr. Pina M. Bhatt",
        designation: "Principal, GTU-ITR & Professor",
        department: "Mechanical Engineering",
        program: "Degree",
        qualification: "Ph.D. in Mechanical Engineering",
        specialization: "Thermal Engineering, Renewable Energy & Fluid Dynamics",
        type: "teaching",
        isPrincipal: true,
        profileUrl: "https://gtuitr.gtu.ac.in/mechFac.aspx?ID=10",
        email: "principal_gperi@gtu.edu.in",
      },
      {
        name: "Dr. Vivek B. Patel",
        designation: "Associate Professor & Head of Department",
        department: "Mechanical Engineering",
        program: "Degree",
        qualification: "Ph.D. in Mechanical Engineering",
        specialization: "Advanced Manufacturing, Material Science & Welding Technology",
        type: "teaching",
        isHod: true,
        profileUrl: "https://gtuitr.gtu.ac.in/mechFac.aspx?ID=1",
        email: "vivek.patel@gtu.edu.in",
      },
      {
        name: "Dr. Lav Kumar Kaushik",
        designation: "Assistant Professor",
        department: "Mechanical Engineering",
        program: "Degree",
        qualification: "Ph.D. in Mechanical Engineering",
        specialization: "Thermal Science, Heat Transfer & CFD Analysis",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/mechFac.aspx?ID=11",
        email: "lav.kaushik@gtu.edu.in",
      },
      {
        name: "Dr. Kapil Surani",
        designation: "Assistant Professor",
        department: "Mechanical Engineering",
        program: "Degree",
        qualification: "Ph.D. in Mechanical Engineering",
        specialization: "CAD/CAM, Machine Design & Finite Element Analysis (FEA)",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/mechFac.aspx?ID=6",
        email: "kapil.surani@gtu.edu.in",
      },
      {
        name: "Prof. Kedar Badheka",
        designation: "Assistant Professor",
        department: "Mechanical Engineering",
        program: "Degree",
        qualification: "M.E. in Mechanical Engineering",
        specialization: "Industrial Engineering, Production Planning & Metrology",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/mechFac.aspx?ID=3",
        email: "kedar.badheka@gtu.edu.in",
      },
      {
        name: "Prof. Hitesh Patel",
        designation: "Assistant Professor",
        department: "Mechanical Engineering",
        program: "Degree",
        qualification: "M.E. in Mechanical Engineering",
        specialization: "Thermal Power Engineering, IC Engines & Alternate Fuels",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/mechFac.aspx?ID=5",
        email: "hitesh.patel@gtu.edu.in",
      },
      {
        name: "Prof. Milin Pandya",
        designation: "Assistant Professor",
        department: "Mechanical Engineering",
        program: "Degree",
        qualification: "M.E. in Mechanical Engineering",
        specialization: "Automobile Engineering, Dynamics of Machinery & Vibrations",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/mechFac.aspx?ID=7",
        email: "milin.pandya@gtu.edu.in",
      },
      {
        name: "Dr. Arick M. Lakhani",
        designation: "Assistant Professor",
        department: "Mechanical Engineering",
        program: "Degree",
        qualification: "Ph.D. in Mechanical Engineering",
        specialization: "Advanced Tribology, Materials Engineering & Nanotechnology",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/mechFac.aspx?ID=9",
        email: "arick.lakhani@gtu.edu.in",
      },
    ],
    technical: [
      {
        name: "Mr. Mahesh Thakor",
        designation: "Lab Assistant",
        department: "Mechanical Engineering",
        program: "Degree",
        qualification: "Diploma / ITI Mechanical",
        specialization: "Workshop Machinery, Lathe Operations & Welding Bay",
        type: "technical",
      },
      {
        name: "Mr. Pravin Sagar",
        designation: "Lab Assistant",
        department: "Mechanical Engineering",
        program: "Degree",
        qualification: "Diploma in Mechanical Engineering",
        specialization: "Thermal & Fluid Mechanics Laboratories, Material Testing",
        type: "technical",
        profileUrl: "https://gtuitr.gtu.ac.in/mechfac10-new.aspx",
      },
    ],
  },

  // 3. Civil Engineering (Degree)
  "degree-civil": {
    teaching: [
      {
        name: "Dr. Ankit Modi",
        designation: "Assistant Professor & In-Charge HOD",
        department: "Civil Engineering",
        program: "Degree",
        qualification: "Ph.D. in Civil Engineering",
        specialization: "Structural Analysis, Concrete Technology & Earthquake Engineering",
        type: "teaching",
        isHod: true,
        profileUrl: "https://gtuitr.gtu.ac.in/civilFac.aspx?ID=11",
        email: "ankit.modi@gtu.edu.in",
      },
      {
        name: "Prof. Sadanand Sahu",
        designation: "Assistant Professor",
        department: "Civil Engineering",
        program: "Degree",
        qualification: "M.Tech in Geotechnical Engineering",
        specialization: "Soil Mechanics, Foundation Engineering & Slope Stability",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/civilFac.aspx?ID=10",
        email: "sadanand.sahu@gtu.edu.in",
      },
      {
        name: "Prof. Gaurav J. Vyas",
        designation: "Assistant Professor",
        department: "Civil Engineering",
        program: "Degree",
        qualification: "M.E. in Structural Engineering",
        specialization: "Prestressed Concrete, Bridge Design & Steel Structures",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/civilFac.aspx?ID=3",
        email: "gaurav.vyas@gtu.edu.in",
      },
      {
        name: "Prof. Dhaven V. Rughani",
        designation: "Assistant Professor",
        department: "Civil Engineering",
        program: "Degree",
        qualification: "M.E. in Transportation Engineering",
        specialization: "Highway Engineering, Traffic Management & Pavement Design",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/civilFac.aspx?ID=9",
        email: "dhaven.rughani@gtu.edu.in",
      },
      {
        name: "Prof. Akshay Rathod",
        designation: "Assistant Professor",
        department: "Civil Engineering",
        program: "Degree",
        qualification: "M.Tech in Environmental Engineering",
        specialization: "Water Resource Engineering, Hydrology & Waste Management",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/civilFac.aspx?ID=5",
        email: "akshay.rathod@gtu.edu.in",
      },
      {
        name: "Prof. Joseph Sebastian Sibi",
        designation: "Assistant Professor",
        department: "Civil Engineering",
        program: "Degree",
        qualification: "M.E. in Construction Engineering & Management",
        specialization: "Construction Project Management, BIM & Surveying Technologies",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/civilFac.aspx?ID=6",
        email: "joseph.sibi@gtu.edu.in",
      },
    ],
    technical: [
      {
        name: "Mrs. Priyanka Suthar",
        designation: "Lab Assistant",
        department: "Civil Engineering",
        program: "Degree",
        qualification: "Diploma in Civil Engineering",
        specialization: "Concrete Technology, Surveying & Geotech Lab Support",
        type: "technical",
        profileUrl: "https://gtuitr.gtu.ac.in/civilFac8.aspx",
      },
    ],
  },

  // 4. Electrical Engineering (Degree)
  "degree-electrical": {
    teaching: [
      {
        name: "Dr. Piyush Miyani",
        designation: "Head of Department & Assistant Professor",
        department: "Electrical Engineering",
        program: "Degree",
        qualification: "Ph.D. in Electrical Engineering",
        specialization: "Solar PV Systems, Renewable Energy Integration & Power Electronics",
        type: "teaching",
        isHod: true,
        profileUrl: "https://gtuitr.gtu.ac.in/elecFac.aspx?ID=1",
        email: "piyush.miyani@gtu.edu.in",
      },
      {
        name: "Prof. Vishal Koriya",
        designation: "Assistant Professor",
        department: "Electrical Engineering",
        program: "Degree",
        qualification: "M.E. in Electrical Engineering (Power Systems)",
        specialization: "High Voltage Engineering, Power System Protection & Smart Grids",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/elecFac.aspx?ID=3",
        email: "vishal.koriya@gtu.edu.in",
      },
    ],
  },

  // 5. Humanities and Science (Degree)
  "degree-humanities": {
    teaching: [
      {
        name: "Dr. Jignesh B. Patel",
        designation: "Head of Department & Assistant Professor",
        department: "Humanities & Sciences",
        program: "Degree",
        qualification: "Ph.D. in Mathematics",
        specialization: "Applied Mathematics, Numerical Methods & Statistical Analysis",
        type: "teaching",
        isHod: true,
        profileUrl: "https://gtuitr.gtu.ac.in/humanFac.aspx?ID=2",
        email: "jignesh.patel@gtu.edu.in",
      },
      {
        name: "Dr. Maulik Joshi",
        designation: "Assistant Professor",
        department: "Humanities & Sciences",
        program: "Degree",
        qualification: "Ph.D. in Physics",
        specialization: "Engineering Physics, Condensed Matter Physics & Optics",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/humanFac.aspx?ID=4",
        email: "maulik.joshi@gtu.edu.in",
      },
      {
        name: "Dr. Prerak Patel",
        designation: "Assistant Professor",
        department: "Humanities & Sciences",
        program: "Degree",
        qualification: "Ph.D. in Chemistry",
        specialization: "Applied Chemistry, Material Characterization & Environmental Science",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/humanFac.aspx?ID=5",
        email: "prerak.patel@gtu.edu.in",
      },
      {
        name: "Prof. Chetna Agarwal",
        designation: "OSD Assistant Professor",
        department: "Humanities & Sciences",
        program: "Degree",
        qualification: "M.A., M.Phil in English Literature & Linguistics",
        specialization: "Effective Technical Communication, Professional Ethics & Soft Skills",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/humanFac.aspx?ID=6",
        email: "chetna.agarwal@gtu.edu.in",
      },
    ],
  },

  // 6. Computer Engineering (Diploma)
  "diploma-computer": {
    teaching: [
      {
        name: "Prof. Alok Patel",
        designation: "Lecturer in Computer Engineering",
        department: "Computer Engineering (Diploma)",
        program: "Diploma",
        qualification: "B.E. / M.Tech in Computer Engineering",
        specialization: "Web Technologies, Object-Oriented Programming & Database Systems",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/compFac_diploma.aspx?ID=8",
        email: "alok.patel@gtu.edu.in",
      },
      {
        name: "Prof. Jeel Patel",
        designation: "Lecturer in Computer Engineering",
        department: "Computer Engineering (Diploma)",
        program: "Diploma",
        qualification: "B.E. / M.E. in Computer Engineering",
        specialization: "Computer Networks, Operating Systems & Python Programming",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/compFac_diploma.aspx?ID=10",
        email: "jeel.patel@gtu.edu.in",
      },
      {
        name: "Prof. Harshwardhan R. Chaudhari",
        designation: "Lecturer in Computer Engineering",
        department: "Computer Engineering (Diploma)",
        program: "Diploma",
        qualification: "B.E. in Computer Engineering",
        specialization: "C/C++ Programming, Data Structures & Software Engineering",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/compFac_diploma.aspx?ID=9",
        email: "harshwardhan.chaudhari@gtu.edu.in",
      },
    ],
  },

  // 7. Civil Engineering (Diploma)
  "diploma-civil": {
    teaching: [
      {
        name: "Prof. Naman N. Bhavsar",
        designation: "Lecturer in Civil Engineering",
        department: "Civil Engineering (Diploma)",
        program: "Diploma",
        qualification: "B.E. / M.E. in Civil Engineering",
        specialization: "Surveying, Building Construction & Structural Drawing",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/civilFac_diploma.aspx?ID=5",
        email: "naman.bhavsar@gtu.edu.in",
      },
      {
        name: "Prof. Pruthav Barot",
        designation: "OSD Assistant Professor / Lecturer",
        department: "Civil Engineering (Diploma)",
        program: "Diploma",
        qualification: "M.E. in Civil Engineering",
        specialization: "Hydraulics, Estimating & Costing, Construction Materials",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/civilFac_diploma.aspx?ID=3",
        email: "pruthav.barot@gtu.edu.in",
      },
      {
        name: "Prof. Rajat Dharmeshkumar Priyadarshi",
        designation: "Lecturer in Civil Engineering",
        department: "Civil Engineering (Diploma)",
        program: "Diploma",
        qualification: "B.E. / M.E. in Civil Engineering",
        specialization: "Concrete Technology, Environmental Engineering & Geotechnical Practice",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/civilFac_diploma.aspx?ID=6",
        email: "rajat.priyadarshi@gtu.edu.in",
      },
    ],
  },

  // 8. Mechanical Engineering (Diploma)
  "diploma-mechanical": {
    teaching: [
      {
        name: "Prof. Pankaj Prajapati",
        designation: "Lecturer in Mechanical Engineering",
        department: "Mechanical Engineering (Diploma)",
        program: "Diploma",
        qualification: "B.E. / M.E. in Mechanical Engineering",
        specialization: "Manufacturing Processes, Workshop Practice & Metrology",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/mechFac_diploma.aspx?ID=1",
        email: "pankaj.prajapati@gtu.edu.in",
      },
      {
        name: "Prof. Ashutosh Gohel",
        designation: "Lecturer in Mechanical Engineering",
        department: "Mechanical Engineering (Diploma)",
        program: "Diploma",
        qualification: "B.E. / M.Tech in Mechanical Engineering",
        specialization: "Thermal Engineering, Fluid Mechanics & Hydraulic Machines",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/mechFac_diploma.aspx?ID=5",
        email: "ashutosh.gohel@gtu.edu.in",
      },
      {
        name: "Dr. Yogeshkumar Khimsuriya",
        designation: "Lecturer in Mechanical Engineering",
        department: "Mechanical Engineering (Diploma)",
        program: "Diploma",
        qualification: "Ph.D. / M.E. in Mechanical Engineering",
        specialization: "Machine Design, Theory of Machines & CAD Drafting",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/mechFac_diploma.aspx?ID=7",
        email: "yogesh.khimsuriya@gtu.edu.in",
      },
      {
        name: "Prof. Kaushal Khamar",
        designation: "Lecturer in Mechanical Engineering",
        department: "Mechanical Engineering (Diploma)",
        program: "Diploma",
        qualification: "B.E. / M.E. in Mechanical Engineering",
        specialization: "Industrial Engineering, Automobile Systems & Tool Engineering",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/mechFac_diploma.aspx?ID=6",
        email: "kaushal.khamar@gtu.edu.in",
      },
    ],
  },

  // 9. Electrical Engineering (Diploma)
  "diploma-electrical": {
    teaching: [
      {
        name: "Prof. Dharmesh Kiritkumar Patel",
        designation: "Lecturer in Electrical Engineering",
        department: "Electrical Engineering (Diploma)",
        program: "Diploma",
        qualification: "B.E. / M.E. in Electrical Engineering",
        specialization: "Electrical Machines, Circuits & Wiring Installations",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/elecFac_diploma.aspx?ID=5",
        email: "dharmesh.patel@gtu.edu.in",
      },
      {
        name: "Mr. ShabbirAli Champa",
        designation: "Lecturer in Electrical Engineering",
        department: "Electrical Engineering (Diploma)",
        program: "Diploma",
        qualification: "B.E. in Electrical Engineering",
        specialization: "Power Systems, Transmission & Switchgear Protection",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/elecFac_diploma.aspx?ID=3",
        email: "shabbirali.champa@gtu.edu.in",
      },
      {
        name: "Prof. Divyang Pankajbhai Raval",
        designation: "Lecturer in Electrical Engineering",
        department: "Electrical Engineering (Diploma)",
        program: "Diploma",
        qualification: "B.E. / M.E. in Electrical Engineering",
        specialization: "Basic Electrical, Instrumentation & Sensor Systems",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/elecFac_diploma.aspx?ID=6",
        email: "divyang.raval@gtu.edu.in",
      },
      {
        name: "Prof. Jansari Bhargav Dineshkumar",
        designation: "Lecturer in Electrical Engineering",
        department: "Electrical Engineering (Diploma)",
        program: "Diploma",
        qualification: "B.E. in Electrical Engineering",
        specialization: "Industrial Automation, PLC Programming & Motor Drives",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/elecFac_diploma.aspx?ID=4",
        email: "bhargav.jansari@gtu.edu.in",
      },
    ],
    technical: [
      {
        name: "Prof. Rajdeepsinh Chavda",
        designation: "Lab Assistant",
        department: "Electrical Engineering (Diploma)",
        program: "Diploma",
        qualification: "Diploma in Electrical Engineering",
        specialization: "Machines Laboratory & High Voltage Testing Bay",
        type: "technical",
        profileUrl: "https://gtuitr.gtu.ac.in/elecFac_diploma.aspx?ID=7",
      },
    ],
  },

  // 10. Humanities and Science (Diploma)
  "diploma-humanities": {
    teaching: [
      {
        name: "Mr. MehulKumar Thakor",
        designation: "Lecturer in Mathematics",
        department: "Humanities & Sciences (Diploma)",
        program: "Diploma",
        qualification: "M.Sc. in Mathematics",
        specialization: "Engineering Mathematics, Applied Algebra & Calculus",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/humanFac_diploma.aspx?ID=2",
        email: "mehul.thakor@gtu.edu.in",
      },
      {
        name: "Mr. Jay D. Patel",
        designation: "Lecturer in Physics",
        department: "Humanities & Sciences (Diploma)",
        program: "Diploma",
        qualification: "M.Sc. in Physics",
        specialization: "Applied Physics, Optics & Laboratory Experiments",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/humanFac_diploma.aspx?ID=1",
        email: "jay.patel@gtu.edu.in",
      },
      {
        name: "Prof. Mahmmad Azruddin D. Kureshi",
        designation: "Lecturer in English & Communication",
        department: "Humanities & Sciences (Diploma)",
        program: "Diploma",
        qualification: "M.A. in English",
        specialization: "Communication Skills, Technical Writing & Language Lab",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/humanFac_diploma.aspx?ID=5",
        email: "azruddin.kureshi@gtu.edu.in",
      },
      {
        name: "Prof. Shah Divy Balmukund",
        designation: "Lecturer in Applied Sciences",
        department: "Humanities & Sciences (Diploma)",
        program: "Diploma",
        qualification: "M.Sc. in Chemistry",
        specialization: "Engineering Chemistry & Environmental Studies",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/humanFac_diploma.aspx?ID=4",
        email: "divy.shah@gtu.edu.in",
      },
    ],
  },

  // 11. Integrated M.Sc. IT & PGDCS
  "msc-it": {
    teaching: [
      {
        name: "Dr. Vishal G. Barot",
        designation: "Program Coordinator & Head of Department",
        department: "Computer Engineering & IT",
        program: "Postgraduate",
        qualification: "Ph.D. in Computer Science & Engineering",
        specialization: "AI/ML, Deep Learning & Enterprise Big Data Architecture",
        type: "teaching",
        isHod: true,
        profileUrl: "https://gtuitr.gtu.ac.in/compFac.aspx?ID=31",
        email: "vishal.barot@gtu.edu.in",
      },
      {
        name: "Prof. Hemalben M. Patel",
        designation: "Assistant Professor",
        department: "Computer Engineering & IT",
        program: "Postgraduate",
        qualification: "M.E. in Computer Engineering",
        specialization: "Cloud Computing, Microservices & Cyber Infrastructure",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/compFac.aspx?ID=29",
        email: "hemal.patel@gtu.edu.in",
      },
      {
        name: "Prof. Shilpa Vasava",
        designation: "Assistant Professor",
        department: "Computer Engineering & IT",
        program: "Postgraduate",
        qualification: "M.E. in Computer Engineering",
        specialization: "Full-Stack Web Development, Node.js & React Frameworks",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/compFac.aspx?ID=19",
        email: "shilpa.vasava@gtu.edu.in",
      },
      {
        name: "Prof. Vijay Punjabhai Khata",
        designation: "Assistant Professor",
        department: "Computer Engineering & IT",
        program: "Postgraduate",
        qualification: "M.Tech / M.E. in Computer Engineering",
        specialization: "Applied Algorithms, Database Optimization & Systems Architecture",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/compFac.aspx?ID=27",
        email: "vijay.khata@gtu.edu.in",
      },
    ],
  },

  pgdcs: {
    teaching: [
      {
        name: "Dr. Vishal G. Barot",
        designation: "Cyber Security Academic Coordinator & HOD",
        department: "Computer Engineering & Cyber Defense",
        program: "Postgraduate",
        qualification: "Ph.D. in Computer Science & Engineering",
        specialization: "Network Security, Cryptography & Threat Intelligence",
        type: "teaching",
        isHod: true,
        profileUrl: "https://gtuitr.gtu.ac.in/compFac.aspx?ID=31",
        email: "vishal.barot@gtu.edu.in",
      },
      {
        name: "Prof. Hemalben M. Patel",
        designation: "Assistant Professor & Cyber Defense Lead",
        department: "Computer Engineering & Cyber Defense",
        program: "Postgraduate",
        qualification: "M.E. in Computer Engineering",
        specialization: "SOC Operations, Incident Response & Digital Forensics",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/compFac.aspx?ID=29",
        email: "hemal.patel@gtu.edu.in",
      },
      {
        name: "Dr. Piyush Miyani",
        designation: "Adjunct Faculty / Advisor",
        department: "Cyber Physical Systems",
        program: "Postgraduate",
        qualification: "Ph.D. in Electrical Engineering",
        specialization: "SCADA & Industrial Control Systems (ICS) Security",
        type: "teaching",
        profileUrl: "https://gtuitr.gtu.ac.in/elecFac.aspx?ID=1",
        email: "piyush.miyani@gtu.edu.in",
      },
    ],
  },
};
